version: "3.7"

services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=${DATABASE_NAME}"
      - "POSTGRES_USER=${DATABASE_USERNAME}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DATABASE_NAME} -U $${DATABASE_USERNAME}" ]
      interval: 5s
      retries: 5
    networks:
      - proxy_net

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./tmp/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
    networks:
      - proxy_net

networks:
  proxy_net:
    name: internal_network
