#! /bin/bash
touch .env
echo "NESTJS_PORT=$NESTJS_PORT" >> .env
echo "NESTJS_SECRET_KEY=$NESTJS_SECRET_KEY" >> .env
echo "JWT_TOKEN_EXPIRE_DAYS=$JWT_TOKEN_EXPIRE_DAYS" >> .env
echo "JWT_REFRESH_TOKEN_EXPIRE_DAYS=$JWT_REFRESH_TOKEN_EXPIRE_DAYS" >> .env

echo "DATABASE_HOST=$DATABASE_HOST" >> .env
echo "DATABASE_NAME=$DATABASE_NAME" >> .env
echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> .env
echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env
echo "DATABASE_PORT=$DATABASE_PORT" >> .env
echo "DATABASE_URL=$DATABASE_URL" >> .env

echo "REDIS_HOST=$REDIS_HOST" >> .env
echo "REDIS_PORT=$REDIS_PORT" >> .env
echo "REDIS_PASSWORD=$REDIS_PASSWORD" >> .env
echo "REDIS_EXPIRE_HOURS=$REDIS_EXPIRE_HOURS" >> .env